---
- name: Sync folder from Ansible control machine to Windows machine
  hosts: windows_hosts
  tasks:
    - name: run ps1 file in  Windows machine
      ansible.windows.win_shell: C:\script.ps1
      args:
        no_profile: true

